In [1]:
%matplotlib inline
import numpy as np
from keras.datasets import mnist
from sklearn.model_selection import StratifiedShuffleSplit
import time
from random import randrange
from past.builtins import xrange
import matplotlib.pyplot as plt
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'
W = np.random.randn(785, 10) * 0.0001


Using TensorFlow backend.


In [2]:
X = np.array([[1,2],[3,4],[5,6]])
print(X)
print(X.T)
y = np.array([0,1,1,0,1,1,1,1,1,1])
print(y)
print(np.max(y))


[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
[0 1 1 0 1 1 1 1 1 1]
1


In [3]:
num_train=10000
batch_size=100
idx = np.random.choice(range(num_train),batch_size, replace = False)
print(idx)
print(type(idx))

[5376 8077  812  562  643 4786 4215  150 7662 1001 8128 7303 4600 5765
  766 5198 6255 3906 6673 8258 7767 5098 4143 2924 8308 4286 8850 5692
  404 3512  997 9216 1027 9514 3998 4320 3018 2715 7986 7216 1517 3437
 1524 3142 3936 2811 6143 6954 2349 6972 4421 8628 1526 3671 8125 2828
 9120 7773 5770 8610 2093 2642 5460 4453  587 4408 3997 6793 9655 4490
 5648 6350  832 3753 5278 9347 1980  195 9741 5506 3349 6494 8369 7621
 5891 9585 7143 2903 6597 5710 4122 1391  238 2875 1324 4153  407  798
 1183   11]
<class 'numpy.ndarray'>


In [4]:
batch_size = 10
dim = 3
num_train = 5000
X = np.random.randn(num_train,dim)
X_batch = np.zeros((batch_size,dim))
y_batch = np.zeros(batch_size)
print(np.shape(X_batch))
print(np.shape(y_batch))

idx = np.random.choice(range(num_train),batch_size, replace = False)
X_batch[range(batch_size)] = X[idx]

print(X_batch)

(10, 3)
(10,)
[[-1.07954664  0.15835643  0.64480203]
 [ 0.59628307 -0.44682223  0.16945456]
 [ 0.50878724 -1.19945207 -0.93419787]
 [-1.92860435 -0.61779429  1.47913223]
 [ 0.91053702  0.28296675  0.96640112]
 [-0.37429145  0.8346396   1.22381309]
 [-0.45665831 -0.17000692 -0.74344415]
 [-0.14644802 -0.88530384 -1.28638189]
 [-0.05066554 -0.63396329 -0.31551895]
 [ 0.55217028  1.57368879  0.96535042]]


In [5]:
d1 = [1,4,2,3]
print(np.argmax(d1))

1


In [6]:
scores = np.array([[0.2,0.8],[0.5,0.5],[0.7,0.3],[0.4,0.6]])
N = scores.shape[0]
y_pred = np.zeros((N,))
print(y_pred)
# y_pred[range(N)] = 
print(np.argmax(scores,axis = 1))
print(type(np.argmax(scores,axis = 1)))

y_pred[:] = np.argmax(scores,axis = 1)[:]
print(y_pred)





[0. 0. 0. 0.]
[1 0 0 1]
<class 'numpy.ndarray'>
[1. 0. 0. 1.]


In [7]:
a = [[5,12],[3,4]]
print(np.linalg.norm(a,axis=1))

[13.  5.]


In [18]:
w = np.array([[1,2],[3,4],[-1,2]])
print (np.max(w))
print (np.min(w))
print(type(w[0][0]))

4
-1
<class 'numpy.int64'>


In [24]:
fo = open("best_W.txt", 'w')
fo.write("fdddd\n")
fo.write("fdddd\n")
fo.write("fdddd\n")


6

In [41]:
matrix = open('myfile.txt').read()
# matrix = [item.split() for item in matrix.split('\n')[:-1]]
# matrix = [item.split() for item in matrix.split('\n')[:-2]]
print(matrix)
print(matrix.split('\n'))
print(type(matrix.split('\n')))

g = np.array([[1,2],[3,4],[5,6]])
a = [g[i][1] for i in range(len(g))]

print(a)

1 2 3
4 5 6
7 8 9

['1 2 3', '4 5 6', '7 8 9', '']
<class 'list'>
[2, 4, 6]
