In [1]:
import numpy as np

hidden_layer_sizes = [500,100] * 10
print(hidden_layer_sizes)
print(type(hidden_layer_sizes))

[500, 100, 500, 100, 500, 100, 500, 100, 500, 100, 500, 100, 500, 100, 500, 100, 500, 100, 500, 100]
<class 'list'>


In [2]:
D = np.random.randn(1000, 500)
print(D.shape)
print(type(D))
print(D)



(1000, 500)
<class 'numpy.ndarray'>
[[ 0.61253738  0.24998258 -0.18888326 ...  1.68843639 -0.3203503
  -0.39845768]
 [-1.42099853  0.63997424  0.96670865 ... -0.85032387  0.79937474
  -1.8706645 ]
 [ 0.01282422 -0.2621758   0.82837506 ...  0.31145755 -1.05480452
  -1.33671399]
 ...
 [-0.76166294 -1.44274356 -1.62991794 ... -0.17431064  0.14708198
  -0.39984372]
 [ 0.2358239  -0.33435611  0.66083409 ... -0.14028701  1.87048744
   1.68757652]
 [-0.93248284  0.09462419 -0.43241251 ...  1.15884245  0.1766981
  -1.89148981]]


In [3]:
a1 = np.array([3, 7, 6, 9, 0, 3])
not_n = 6
a2 = a1 != not_n
print(a2)
a1[a2] = 0
print(a1)

[ True  True False  True  True  True]
[0 0 6 0 0 0]


In [4]:
idx_list = []
# for i in range(len(unique)):
#     if count[i] <= n_sampling:
#         idx_list.append(np.where(y == unique[i])[0])
#         continue
#     idx = np.where(y == unique[i])[0]
#     idx = np.random.choice(idx, n_sampling, replace = False)
#     idx_list.append(idx)
y = np.array([0,0,0,1,1,0,1,0,0,1,0,1])
print(y == 1)
print(np.where(y == 1))
print(type(np.where(y == 1)))

    

[False False False  True  True False  True False False  True False  True]
(array([ 3,  4,  6,  9, 11]),)
<class 'tuple'>


In [5]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = a.reshape((3,3))
print(b.shape)
print(b.shape[1])



(3, 3)
3


In [6]:
def rel_error(x, y):
  """ returns relative error """
  return np.max(np.abs(x - y) / (np.maximum(1e-8, np.abs(x) + np.abs(y))))


In [7]:
for i in range(1,10):
    print(i)


1
2
3
4
5
6
7
8
9


In [8]:
a = [1,2,3,4,5,6,7,8,9]
b = a[+2 *3:]

print(b)

[7, 8, 9]


In [9]:
a = np.empty((9,))
print(a)
print(type(a))
print(len(a.shape))
print(a.shape)

[4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323 3.0e-323 3.5e-323 4.0e-323
 4.4e-323]
<class 'numpy.ndarray'>
1
(9,)


In [10]:
B = lambda x: x # linear activation
print(a)
print(B)
B(a)

[4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323 3.0e-323 3.5e-323 4.0e-323
 4.4e-323]
<function <lambda> at 0x7f01c6e23b70>


array([4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323, 2.5e-323, 3.0e-323,
       3.5e-323, 4.0e-323, 4.4e-323])

In [11]:
a = np.array(range(9))
print(a)
print(a.reshape(*(3,3)))


[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
data = np.arange(6).reshape((3,2))
print(data)
print(np.average(data))
g1 = np.sum([[0, 1], [0, 5]], axis=0)
g2 = np.average([[0, 1], [0, 5]], axis=0)

print("g1 = {}".format(g1))
print("g2 = {}".format(g2))

[[0 1]
 [2 3]
 [4 5]]
2.5
g1 = [0 6]
g2 = [0. 3.]


In [18]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a*b)

[ 4 10 18]
